### ISSUE TITLE
Possible volume conflict between SwiftSpeech and AVAudioPlayer?

### ISSUE THREAD

**Issue by rabbigarfinkel** [Cay-Zhang/SwiftSpeech#10]
My app involves both SwiftSpeech's features and sound effects through SwiftySound. All sound effects work fine in the simulator, but on the device all sound effects stop working once the SwiftSpeech button is pressed. I have one button that makes a "click" noise when pressed. It works until I press the SwiftSpeech button.

If I press the SwiftSpeech button first, I get a sound effect the first time, but then not for subsequent presses.

I made a new, simple project without SwiftSpeech just to test the sound, and everything worked fine on the device. I also switched out SwiftySound and used the normal AVAudioPlayer procedure, and the sound works that way, too.

So the only thing I can think of is that there is a conflict between SwiftSpeech and the sound effects. Is it possible that SwiftSpeech is turning off my sound effects? If so, how do I turn them back on? My code appears below:

`import SwiftUI
import SwiftSpeech
import SwiftySound
import AVFoundation
import AudioToolbox

// VIEW MODEL
struct ContentView: View {
    
    let emojiArray = ["🐵","🦍","🐶","🐺","🦊","🦝","🐱","🦁","🐅","🐴","🦓","🦌","🐮","🐷","🐐","🐪","🦙","🦒","🐘","🦏","🦛","🐁","🐀","🐰","🦇","🐻","🐨","🐼","🦘","🦃","🐔","🐧","🦅","🦆","🦢","🦉","🦚","🐸","🐊","🐢","🦎","🐍","🐳","🐬","🐟","🐙","🐌","🦋","🐜","🐝","🐞","🦗","🕷","🦂","🦟"]

    @State private var emoji = ""
    @State private var nextEmoji = ""
    @State private var text = "What is this? (Press and Hold)"
    @State private var theDescription = ""
    @State var isCorrect:Bool
    @State var player = AVAudioPlayer()
    
    var body: some View {
        
        ZStack(alignment:.top) {
        VStack(alignment: .center) {
            
            Text (emoji).font(.system(size: 200, weight: .bold, design: .default))
                .onAppear() {
                    emoji = emojiArray.randomElement() ?? "none"
                   
                    theDescription = emoji.applyingTransform(.toUnicodeName, reverse: false) ?? "None"
                    print (theDescription) // get the emoji's unicode name
                }

        Text (text)
                .onAppear {
                    SwiftSpeech.requestSpeechRecognitionAuthorization()
                }
          .padding()
            
            SwiftSpeech.RecordButton()
            }
                .swiftSpeechRecordOnHold()
                .onRecognize { _, result in
                    text = result.bestTranscription.formattedString
                    print (text)
                    self.text = text
                    if theDescription.contains(self.text.uppercased()) == true {
                        
                        print ("That's right")
                        text = "That's right!"
                        isCorrect = true
                        playRightSound() 
                     
                    }
                    else {print ("That's wrong")
                        text = "Try again!"
                        isCorrect = false
                        playWrongSound()
                    }
                        
                } handleError: { _, _ in }
        
        Spacer()
            
        Button("Change Animal") {
            nextEmoji = emojiArray.randomElement() ?? "none"
            while nextEmoji == emoji {
                
                nextEmoji = emojiArray.randomElement() ?? "none"
                
            }
            
            playClickSound()
            emoji = nextEmoji
            text = "What is this? (Press and hold)"
            theDescription = emoji.applyingTransform(.toUnicodeName, reverse: false) ?? "None"
            print (theDescription)
                }
      
            }
            
        }
    
    func playRightSound(){
   
    print ("Playing right sound")
    
    Sound.play(file:"yay.wav")
   
           }

     func playWrongSound() {
        
     Sound.play(file:"raspberry.wav")
        
    }
    
    func playClickSound() {
        
        Sound.play(file:"click.wav")
       
    }
    
    struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        
        ContentView(isCorrect:true)
        
    }
   
}

}

`

**Comment by Cay-Zhang** [comment]
Hi,

SwiftSpeech uses a record-only configuration by default. To allow audio playback simultaneously, you need to configure your audio session's category to be [`playAndRecord`](https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616568-playandrecord).

You can do exactly that by passing a session configuration to your record modifiers.

```swift
.swiftSpeechRecordOnHold(sessionConfiguration: .init(audioSessionConfiguration: .playAndRecord))
```

**Comment by rabbigarfinkel** [comment]
Thank you, it works perfectly now!

EG


**********************************

Order my book from JPS <https://bit.ly/2KCIGm7>

Order my book from Amazon <https://amzn.to/2QCEmq8>

Check out my website <http://www.eligarfinkel.com/>



 <http://www.eligarfinkel.com/>
