### ISSUE TITLE
Speech Recognition string does not match a (hard coded) string

### ISSUE THREAD

**Issue by ItsmeKY** [Cay-Zhang/SwiftSpeech#7]
I assign the speech recognition string to a **@State var speechRecogText** and I check if the other hardcoded string **private var text** contains the string from the speech recognition. This works properly and prints _contains..._ in English. But with the Arabic Language, it does not work.

``` swift
@State var speechRecogText: String = ""
private var text: String = "قل"

if textFieldText.contains(speechRecogText) {
            print("contaions voice text")
        } else {
            print("doesn't contain voice text")
        }

Console
// doesn't contain voice text
```

However when I try to swap the variables like this:

``` swift
if speechRecogText.contains(textFieldText) {
            print("contains text")
        } else {
            print("doesnt contain text")
        }

Console
// contains text
```

What might be the reason for this? Does it have to do anything with the Language or how Strings actually behave?

**Comment by Cay-Zhang** [comment]
You might want to write some tests to figure out how Swift is handling the Arabic language. I don't think this issue is related to SwiftSpeech.
