### ISSUE TITLE
Swift Playgrounds Compatibility

### ISSUE THREAD

**Issue by JanX2** [Cay-Zhang/SwiftSpeech#9]
@Cay-Zhang 
Adding this to Swift Playgrounds on iPadOS results in an error message: “package doesn't have version tags”. I fixed  that in my fork by adding a new tag removing the “v“ prefix. 

You can also have a look at this:
https://github.com/erikdoe/ocmock/issues/496

**Comment by Cay-Zhang** [comment]
It should work in the latest version of Swift Playgrounds now.

**Comment by JanX2** [comment]
Thanks!
